/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Create an org with the caller as its owner. An `Idempotency-Key` header makes a retry
         *     return the first response instead of creating a second org (spec §7).
         */
        post: operations["create_api_v1_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_orgs__org_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description Delete the org, its members, invitations and everything it owns. The caller must type
         *     the org's name (spec §7), sent as `?confirm_name=`: a DELETE can't carry a body through
         *     CloudFront. The audit log keeps its records.
         */
        delete: operations["delete_api_v1_orgs__org_id__delete"];
        options?: never;
        head?: never;
        /** Rename */
        patch: operations["rename_api_v1_orgs__org_id__patch"];
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Log
         * @description The org's audit events, newest first, a page at a time (spec §7's cursor pagination).
         */
        get: operations["audit_log_api_v1_orgs__org_id__audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_v1_orgs__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove
         * @description Remove a member, or leave when `{user_id}` is the caller (spec §6.4).
         */
        delete: operations["remove_api_v1_orgs__org_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Set Role */
        patch: operations["set_role_api_v1_orgs__org_id__members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitations */
        get: operations["invitations_api_v1_orgs__org_id__invitations_get"];
        put?: never;
        /** Invite */
        post: operations["invite_api_v1_orgs__org_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_api_v1_orgs__org_id__invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept
         * @description Join an org with an invitation's token, from the link's fragment (spec §6.3).
         */
        post: operations["accept_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Uploads
         * @description The org's uploads, newest first, a page at a time.
         */
        get: operations["uploads_api_v1_orgs__org_id__uploads_get"];
        put?: never;
        /**
         * Create
         * @description Register a file and get a presigned PUT for it, valid for 5 minutes. It counts against
         *     the org's 20 uploads a day; an `Idempotency-Key` makes a retry return the same upload.
         */
        post: operations["create_api_v1_orgs__org_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upload
         * @description One upload: its status and, once analyzed, its statistics.
         */
        get: operations["upload_api_v1_orgs__org_id__uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Findings
         * @description The org's findings, newest first, or most severe first and then newest with
         *     `sort=severity` (Plan 6b). Filters, combined: any of the given statuses, severity, detector,
         *     upload, the assignee (`me` or `none`) and `since` a moment (Plan 6d). A cursor works only
         *     with the order it was made for.
         */
        get: operations["findings_api_v1_orgs__org_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finding
         * @description One finding with its evidence, techniques and events. Its `ETag` is the version that
         *     triage (Plan 4c) will require in `If-Match`.
         */
        get: operations["finding_api_v1_orgs__org_id__findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Triage
         * @description Change the finding's status, its assignee, or both. `If-Match` must carry the `ETag` of
         *     the version the caller read: without it the answer is 428, and if someone changed the
         *     finding since, 412 with the current `ETag`.
         */
        patch: operations["triage_api_v1_orgs__org_id__findings__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/findings/{finding_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Comment
         * @description Add a comment to the finding's history. An `Idempotency-Key` makes a retry return the
         *     same comment instead of posting it twice. The audit log records that a comment was made,
         *     never its text.
         */
        post: operations["comment_api_v1_orgs__org_id__findings__finding_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/findings/{finding_id}/ai-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun
         * @description Explain the finding again: 202 when it's queued, or 200 with the answer when it's already
         *     explained for the current model and prompt.
         */
        post: operations["rerun_api_v1_orgs__org_id__findings__finding_id__ai_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/findings/{finding_id}/ai-analyses/{analysis_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rate
         * @description Rate one of the finding's explanations up or down; a new rating replaces the last. Only an
         *     explanation that succeeded can be rated (409 otherwise).
         */
        put: operations["rate_api_v1_orgs__org_id__findings__finding_id__ai_analyses__analysis_id__feedback_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage
         * @description The last `days` UTC days of AI use (30 unless asked; at most 90), newest first.
         */
        get: operations["usage_api_v1_orgs__org_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attack-techniques/{technique_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Technique
         * @description One ATT&CK technique (`T1046`, `T1110.001`) from the version NetTriage ships, with
         *     MITRE's notice and license.
         */
        get: operations["technique_api_v1_attack_techniques__technique_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptIn */
        AcceptIn: {
            /** Token */
            token: string;
        };
        /**
         * AiAnalysisOut
         * @description AI-generated: the UI labels it so, with the model and prompt version (spec §8.4).
         */
        AiAnalysisOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Provider */
            provider: string;
            /** Model Id */
            model_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Output Schema Version */
            output_schema_version: string;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Error Code */
            error_code: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Cost Usd */
            cost_usd: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Feedback */
            feedback: ("up" | "down") | null;
            /** Feedback By */
            feedback_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** @enum {string} */
        AiStatus: "pending" | "succeeded" | "failed" | "skipped_budget" | "invalid_output";
        /** AuditEventOut */
        AuditEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Actor Type */
            actor_type: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string | null;
            /** Target Id */
            target_id: string | null;
            /** Outcome */
            outcome: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** AuditLogOut */
        AuditLogOut: {
            /** Events */
            events: components["schemas"]["AuditEventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CommentIn */
        CommentIn: {
            /** Text */
            text: string;
        };
        /** CreatedInvitationOut */
        CreatedInvitationOut: {
            invitation: components["schemas"]["InvitationOut"];
            /** Invite Url */
            invite_url: string;
        };
        /** CreatedUploadOut */
        CreatedUploadOut: {
            upload: components["schemas"]["UploadOut"];
            /** Upload Url */
            upload_url: string;
            /** Upload Headers */
            upload_headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** DayUsageOut */
        DayUsageOut: {
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: string;
            /**
             * Day
             * Format: date
             */
            day: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Src Ip */
            src_ip: string;
            /** Dst Ip */
            dst_ip: string;
            /** Src Port */
            src_port: number;
            /** Dst Port */
            dst_port: number;
            /** Protocol */
            protocol: number;
            /** Packets */
            packets: number;
            /** Bytes */
            bytes: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Action */
            action: string;
            /** Line No */
            line_no: number;
        };
        /**
         * FeedbackIn
         * @description A reader's rating of an explanation: `up` or `down` (spec §7).
         */
        FeedbackIn: {
            /**
             * Feedback
             * @enum {string}
             */
            feedback: "up" | "down";
        };
        /** FindingEventOut */
        FindingEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Actor Id */
            actor_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: number;
            severity: components["schemas"]["FindingSeverity"];
            status: components["schemas"]["FindingStatus"];
            /** Title */
            title: string;
            /** Src Ip */
            src_ip: string;
            /** Dst Ip */
            dst_ip: string | null;
            /** Dst Port */
            dst_port: number | null;
            /** Protocol */
            protocol: number | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Assignee Id */
            assignee_id: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            ai_status: components["schemas"]["AiStatus"] | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Techniques */
            techniques: components["schemas"]["FindingTechniqueOut"][];
            /** Events */
            events: components["schemas"]["FindingEventOut"][];
            /** Events Total */
            events_total: number;
            ai_analysis: components["schemas"]["AiAnalysisOut"] | null;
        };
        /** @enum {string} */
        FindingSeverity: "low" | "medium" | "high" | "critical";
        /** @enum {string} */
        FindingStatus: "open" | "investigating" | "resolved" | "false_positive";
        /** FindingSummaryOut */
        FindingSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: number;
            severity: components["schemas"]["FindingSeverity"];
            status: components["schemas"]["FindingStatus"];
            /** Title */
            title: string;
            /** Src Ip */
            src_ip: string;
            /** Dst Ip */
            dst_ip: string | null;
            /** Dst Port */
            dst_port: number | null;
            /** Protocol */
            protocol: number | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Assignee Id */
            assignee_id: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            ai_status: components["schemas"]["AiStatus"] | null;
        };
        /** FindingTechniqueOut */
        FindingTechniqueOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Rationale */
            rationale: string | null;
        };
        /** FindingsOut */
        FindingsOut: {
            /** Findings */
            findings: components["schemas"]["FindingSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InvitationIn */
        InvitationIn: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
        };
        /** InvitationOut */
        InvitationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
        };
        /** InvitationsOut */
        InvitationsOut: {
            /** Invitations */
            invitations: components["schemas"]["InvitationOut"][];
        };
        /** LogoutResult */
        LogoutResult: {
            /** Logout Url */
            logout_url: string;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
            /** Csrf Token */
            csrf_token: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** MembersOut */
        MembersOut: {
            /** Members */
            members: components["schemas"]["MemberOut"][];
        };
        /** MembershipOut */
        MembershipOut: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Role */
            role: string;
        };
        /** NameIn */
        NameIn: {
            /** Name */
            name: string;
        };
        /** OrgOut */
        OrgOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
            /** Member Count */
            member_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RerunOut
         * @description `queued` (202): the triage worker explains the finding again. `explained` (200): its
         *     latest analysis for the current model, prompt and input already succeeded, so that answer is
         *     returned and nothing is spent.
         */
        RerunOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "explained";
            ai_analysis: components["schemas"]["AiAnalysisOut"] | null;
        };
        /** RoleIn */
        RoleIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "analyst" | "viewer";
        };
        /** TechniqueOut */
        TechniqueOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tactics */
            tactics: string[];
            /** Description */
            description: string;
            /** Url */
            url: string;
            /** Is Subtechnique */
            is_subtechnique: boolean;
            /** Parent Id */
            parent_id: string | null;
            /** Deprecated */
            deprecated: boolean;
            /** Attack Version */
            attack_version: string;
            /** Notice */
            notice: string;
            /** License */
            license: string;
        };
        /**
         * TriageIn
         * @description A status, an assignee, or both. `"assignee_id": null` unassigns; leaving a field out
         *     leaves it as it is.
         */
        TriageIn: {
            status?: components["schemas"]["FindingStatus"] | null;
            /** Assignee Id */
            assignee_id?: string | null;
        };
        /** UploadIn */
        UploadIn: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_upload" | "processing" | "analyzed" | "failed" | "expired";
            /** Failure Reason */
            failure_reason: string | null;
            /** Rows Parsed */
            rows_parsed: number | null;
            /** Rows Rejected */
            rows_rejected: number | null;
            /** Rejected Samples */
            rejected_samples: {
                [key: string]: unknown;
            }[];
            /** Findings Truncated */
            findings_truncated: number;
            /** Flow Start */
            flow_start: string | null;
            /** Flow End */
            flow_end: string | null;
            /**
             * Uploaded By
             * Format: uuid
             */
            uploaded_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at: string | null;
        };
        /** UploadsOut */
        UploadsOut: {
            /** Uploads */
            uploads: components["schemas"]["UploadOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * UsageOut
         * @description Newest day first. Days without a model call aren't listed.
         */
        UsageOut: {
            /** Days */
            days: components["schemas"]["DayUsageOut"][];
            totals: components["schemas"]["UsageTotalsOut"];
        };
        /** UsageTotalsOut */
        UsageTotalsOut: {
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login_api_auth_login_get: {
        parameters: {
            query?: {
                return_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResult"];
                };
            };
        };
    };
    logout_all_api_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResult"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    create_api_v1_orgs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_orgs__org_id__delete: {
        parameters: {
            query: {
                confirm_name: string;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_api_v1_orgs__org_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_log_api_v1_orgs__org_id__audit_log_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_v1_orgs__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_v1_orgs__org_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_v1_orgs__org_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invitations_api_v1_orgs__org_id__invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_api_v1_orgs__org_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_orgs__org_id__invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uploads_api_v1_orgs__org_id__uploads_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_orgs__org_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_orgs__org_id__uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_v1_orgs__org_id__findings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FindingStatus"][] | null;
                severity?: components["schemas"]["FindingSeverity"] | null;
                detector?: string | null;
                upload?: string | null;
                assignee?: ("me" | "none") | null;
                since?: string | null;
                sort?: "newest" | "severity";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_api_v1_orgs__org_id__findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    triage_api_v1_orgs__org_id__findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "if-match"?: string | null;
            };
            path: {
                org_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comment_api_v1_orgs__org_id__findings__finding_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_api_v1_orgs__org_id__findings__finding_id__ai_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Already explained: the answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerunOut"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_api_v1_orgs__org_id__findings__finding_id__ai_analyses__analysis_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                finding_id: string;
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_api_v1_orgs__org_id__usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    technique_api_v1_attack_techniques__technique_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technique_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
