import { Link, useSearchParams } from "react-router";
import { signInUrl, useMe } from "../auth/session";
import { SAMPLE_SCAN } from "../landing/sampleScan";
import { ExternalLink } from "../ui/ExternalLink";
import { PortMap } from "../ui/PortMap";
import { SeverityBars } from "../ui/SeverityBars";
import { usePageTitle } from "../ui/usePageTitle";
import { Wordmark } from "../ui/Wordmark";

export const SOURCE_URL = "https://github.com/khajdar1/nettriage";

// The API sends a failed sign-in back here as `/?sign_in=<reason>` (spec §4.1, §6.5).
const SIGN_IN_PROBLEMS: Record<string, string> = {
  expired: "Your sign-in took too long, or started in another browser. Please sign in again.",
  failed: "Sign-in was cancelled or didn't finish. Please try again.",
  disabled: "This account is disabled.",
  unavailable: "Sign-in isn't available right now. Please try again in a few minutes.",
  limited: "Too many sign-in attempts. Please wait a minute, then try again.",
};

const CALLOUTS = [
  { port: 22, name: "ssh" },
  { port: 80, name: "http" },
  { port: 443, name: "https" },
];

function HowItWorks() {
  return (
    <section className="how" id="how" aria-labelledby="how-title">
      <h2 id="how-title">How a finding is made</h2>
      <ol className="steps">
        <li className="step">
          <span className="step-n">1</span>
          <h3>Upload a flow log</h3>
          <p>
            The file goes straight from your browser to storage, checked against its fingerprint.
          </p>
          <p className="artifact mono logline">
            2 123456789012 eni-0f3a <mark>203.0.113.9</mark> 10.0.0.5 51234 <mark>22</mark> 6 1 44
            1696112400 1696112401 REJECT OK
          </p>
        </li>
        <li className="step step-detect">
          <span className="step-n">2</span>
          <h3>Rules find it</h3>
          <p>
            Detectors look for scans, brute force and unusual outbound volume. They decide, not the
            AI.
          </p>
          <dl className="artifact rule">
            <dt>Rule</dt>
            <dd>Port scan, version 1</dd>
            <dt>Saw</dt>
            <dd>150 ports, one source, 5 minutes</dd>
            <dt>ATT&amp;CK</dt>
            <dd>T1046 Network Service Discovery</dd>
          </dl>
        </li>
        <li className="step">
          <span className="step-n">3</span>
          <h3>An AI explains it</h3>
          <p>From the finding's own numbers only, and checked before anyone reads it.</p>
          <blockquote className="artifact ai-quote">
            <span className="ai-label">AI-generated by gpt-oss-20b</span>
            203.0.113.9 tried 150 ports on 10.0.0.5 in five minutes, and every attempt was refused.
            That's reconnaissance: check what else this address reached.
          </blockquote>
        </li>
        <li className="step">
          <span className="step-n">4</span>
          <h3>Your team triages it</h3>
          <p>Status, owner and comments. Every change is kept, and nobody overwrites anybody.</p>
          <ul className="artifact events">
            <li>
              <b>Ana</b> moved it to <span className="state">Investigating</span>
            </li>
            <li>
              <b>Ben</b> took it on
            </li>
          </ul>
        </li>
      </ol>
    </section>
  );
}

/** `/`: what NetTriage does, shown with a finding it wrote (spec §10). */
export function Landing() {
  usePageTitle(null);
  const [params] = useSearchParams();
  const reason = params.get("sign_in") ?? "";
  // Only the reasons above: an inherited name such as `__proto__` is no reason.
  const problem = Object.hasOwn(SIGN_IN_PROBLEMS, reason) ? SIGN_IN_PROBLEMS[reason] : undefined;
  const signedIn = Boolean(useMe().data);
  return (
    <div className="site">
      <header className="site-top">
        <Wordmark to="/" />
        <nav className="site-nav" aria-label="Site">
          <a href="#how">How it works</a>
          <ExternalLink href={SOURCE_URL}>Source code</ExternalLink>
          {signedIn ? (
            <Link className="button button-primary" to="/app">
              Your organizations
            </Link>
          ) : (
            <a className="button button-primary" href={signInUrl("/app")}>
              Sign in
            </a>
          )}
        </nav>
      </header>
      <main id="main">
        <section className="hero">
          <div className="hero-text">
            <p className="finding-kind">
              <SeverityBars level={3} />
              High: port scan
            </p>
            <h1>Port scan of 10.0.0.5 from 203.0.113.9: 150&nbsp;TCP ports in 5&nbsp;minutes</h1>
            <p className="lede">
              NetTriage read <strong>150 lines</strong> of a VPC flow log and wrote that sentence.
              It mapped the scan to MITRE ATT&amp;CK and had it explained, ready for your team to
              triage.
            </p>
            {problem !== undefined && (
              <p role="alert" className="notice notice-error">
                {problem}
              </p>
            )}
            <div className="actions">
              {signedIn ? (
                <Link className="button button-primary" to="/app">
                  Open your organizations
                </Link>
              ) : (
                <a className="button button-primary" href={signInUrl("/app")}>
                  Sign in or sign up
                </a>
              )}
              <a className="text-link" href="#how">
                See how a finding is made
              </a>
            </div>
          </div>
          <PortMap
            ports={SAMPLE_SCAN}
            caption="Ports 0 to 1023 of 10.0.0.5, lit in the order they were probed"
            callouts={CALLOUTS}
            sweep
          />
        </section>
        <HowItWorks />
      </main>
      <footer className="site-foot">
        <span>Runs on AWS in Stockholm. Open source under Apache 2.0.</span>
        <ExternalLink href={SOURCE_URL}>github.com/khajdar1/nettriage</ExternalLink>
      </footer>
    </div>
  );
}
