import { screen, within } from "@testing-library/react";
import { expect, test } from "vitest";
import { fakeApi } from "../test/fakeApi";
import { ME, SIGNED_OUT } from "../test/fixtures";
import { renderAt } from "../test/render";

const SIGN_IN = "/api/auth/login?return_to=%2Fapp";

test("the landing page leads with a finding NetTriage wrote, and offers to sign in", async () => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt("/");

  expect(
    screen.getByRole("heading", {
      level: 1,
      name: /^Port scan of 10\.0\.0\.5 from 203\.0\.113\.9: 150\sTCP ports in 5\sminutes$/,
    }),
  ).toBeInTheDocument();
  expect(await screen.findByRole("link", { name: "Sign in or sign up" })).toHaveAttribute(
    "href",
    SIGN_IN,
  );
  expect(screen.getByRole("link", { name: "Sign in" })).toHaveAttribute("href", SIGN_IN);
  expect(screen.getByRole("link", { name: "NetTriage" })).toHaveAttribute("href", "/");
  expect(document.title).toBe("NetTriage");
});

test("signed in, it opens the person's organizations instead", async () => {
  fakeApi({ "GET /api/v1/me": { body: ME } });

  renderAt("/");

  expect(await screen.findByRole("link", { name: "Open your organizations" })).toHaveAttribute(
    "href",
    "/app",
  );
  expect(screen.getByRole("link", { name: "Your organizations" })).toHaveAttribute("href", "/app");
  expect(screen.queryByRole("link", { name: "Sign in" })).not.toBeInTheDocument();
});

test("the scan's port map says in words what it draws", () => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt("/");

  expect(
    screen.getByRole("figure", {
      name: "Ports 0 to 1023 of 10.0.0.5, lit in the order they were probed",
    }),
  ).toBeInTheDocument();
  expect(screen.getByText("150")).toBeInTheDocument();
});

test("how a finding is made is shown as its four real steps, in order", () => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt("/");

  const section = screen.getByRole("region", { name: "How a finding is made" });
  const list = within(section).getAllByRole("list")[0] as HTMLElement;
  const steps = within(list)
    .getAllByRole("listitem")
    .filter((item) => item.parentElement === list);
  expect(steps.map((step) => within(step).getByRole("heading", { level: 3 }).textContent)).toEqual([
    "Upload a flow log",
    "Rules find it",
    "An AI explains it",
    "Your team triages it",
  ]);
  expect(
    within(steps[2] as HTMLElement).getByText("AI-generated by gpt-oss-20b"),
  ).toBeInTheDocument();
});

test.each([
  ["expired", "Your sign-in took too long, or started in another browser. Please sign in again."],
  ["failed", "Sign-in was cancelled or didn't finish. Please try again."],
  ["disabled", "This account is disabled."],
  ["unavailable", "Sign-in isn't available right now. Please try again in a few minutes."],
  ["limited", "Too many sign-in attempts. Please wait a minute, then try again."],
])("a sign-in that failed with %s says why", (reason, message) => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt(`/?sign_in=${reason}`);

  expect(screen.getByRole("alert")).toHaveTextContent(message);
});

test.each(["<script>", "__proto__", "constructor", "toString"])(
  "a sign-in reason it doesn't know (%s) shows nothing, and the page still works",
  (reason) => {
    fakeApi({ "GET /api/v1/me": SIGNED_OUT });

    renderAt(`/?sign_in=${encodeURIComponent(reason)}`);

    expect(screen.getByRole("heading", { level: 1 })).toBeInTheDocument();
    expect(screen.queryByRole("alert")).not.toBeInTheDocument();
  },
);

test("the source code opens in a new tab that can't reach back", () => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt("/");

  const link = screen.getByRole("link", { name: "Source code" });
  expect(link).toHaveAttribute("href", "https://github.com/khajdar1/nettriage");
  expect(link).toHaveAttribute("target", "_blank");
  expect(link).toHaveAttribute("rel", "noopener noreferrer");
});

test("an address that isn't a page says so and leads home", () => {
  fakeApi({ "GET /api/v1/me": SIGNED_OUT });

  renderAt("/no/such/page");

  expect(screen.getByRole("heading", { level: 1, name: "Page not found" })).toBeInTheDocument();
  expect(screen.getByRole("link", { name: "Go to the home page" })).toHaveAttribute("href", "/");
  expect(screen.getByRole("link", { name: "NetTriage" })).toHaveAttribute("href", "/");
  expect(document.title).toBe("Page not found · NetTriage");
});
